#ifndef _HELP_H_
#define _HELP_H_

static char txt_help[]=
"Mouse:\n"
"\n"
"  move          - highlight the elementary geometrical entity\n"
"                  currently under the mouse pointer and display\n"
"                  its properties in the status bar\n"
"                - size a rubber zoom started with (Ctrl+mouse1)\n"
"  mouse1        - rotate\n"
"                - accept a rubber zoom started by Ctrl+mouse1\n" 
"  Ctrl+mouse1   start (anisotropic) rubber zoom\n" 
"  Shift+mouse1  - zoom (isotropic)\n"
"                - cancel a rubber zoom\n"
"  mouse2        same as Shift+mouse1\n"
"  Ctrl+mouse2   orthogonalize display\n" 
"  mouse3        - pan\n"
"                - cancel a rubber zoom\n"
"                - pop up menu on module name\n"
"                - pop up menu on post-processing view button\n"
"  Ctrl+mouse3   reset viewpoint to default\n"   
"\n"
"Menu bar shortcuts:\n"
"\n"
"  g             go to geometry module\n"
"  Shift+g       show geometry options\n"
"  Shift+i       show statistics window\n" 
"  Ctrl+l        reload all post-processing views\n" 
"  m             go to mesh module\n"
"  Shift+m       show mesh options\n"
"  Ctrl+m        merge file\n" 
"  Shift+o       show general options\n" 
"  Ctrl+o        open file\n" 
"  p             go to post processor module\n"
"  Shift+p       show post-processing general options\n"
"  Ctrl+p        save file by extension\n"
"  Ctrl+q        quit\n"
"  Ctrl+r        remove all post-processing views\n" 
"  Ctrl+s        save mesh\n"
"\n"
"Other shortcuts\n"
"\n"
"  0 or Esc      reload geometry input file\n"
"  1 or F1       mesh curves\n"
"  2 or F2       mesh surfaces\n"
"  3 or F3       mesh volumes\n"
"  Alt+a         hide/show small axes\n" 
"  Alt+Shift+a   hide/show big moving axes\n" 
"  Alt+b         hide/show all post processing scales\n"
"  Alt+c         alternate between predefined color schemes\n"
"  Alt+d         alternate between mesh wire frame, hidden lines and shading modes\n"
"  Alt+f         toggle redraw mode (fast/full)\n" 
"  Alt+l         hide/show geometry lines\n"
"  Alt+Shift+l   hide/show mesh lines\n"
"  Alt+m         toggle visibility of all mesh entities\n"
"  Alt+o         change projection mode\n"
"  Alt+p         hide/show geometry points\n"
"  Alt+Shift+p   hide/show mesh points\n"
"  s             increase animation delay\n"
"  Shift+s       decrease animation delay\n"
"  Alt+s         hide/show geometry surfaces\n"
"  Alt+Shift+s   hide/show mesh surfaces\n"
"  Alt+t         alternate intervals mode for all post-processing views\n" 
"  Alt+v         hide/show geometry volumes\n"
"  Alt+Shift+v   hide/show mesh volumes\n"
"  Alt+x         set X view\n" 
"  Alt+y         set Y view\n" 
"  Alt+z         set Z view\n" 
"\n"
;


#endif
