// Gmsh - Copyright (C) 1997-2021 C. Geuzaine, J.-F. Remacle
//
// See the LICENSE.txt file for license information. Please report all
// issues on https://gitlab.onelab.info/gmsh/gmsh/issues.

#ifndef XPM_ICON_H
#define XPM_ICON_H

#include <FL/Fl_Pixmap.H>

static const char *const gmsh_icon_xpm[] = {
/* columns rows colors chars-per-pixel */
"128 128 44 1 ",
"  c None",
". c #000500",
"X c #000A00",
"o c #0E0F0E",
"O c #051005",
"+ c #0E130E",
"@ c #131413",
"# c #131913",
"$ c #1B1D1B",
"% c #1F221F",
"& c #242424",
"* c #262926",
"= c #2C2C2C",
"- c #2D302D",
"; c #302F30",
": c #343434",
"> c #3B3B3B",
", c #3F403F",
"< c #444444",
"1 c #4C4C4C",
"2 c #535453",
"3 c #5C5C5C",
"4 c #605F60",
"5 c #646464",
"6 c #6C6C6C",
"7 c #737373",
"8 c #7B7B7B",
"9 c #848484",
"0 c #8B8B8B",
"q c #949494",
"w c #9C9C9C",
"e c #A3A3A3",
"r c #ABABAB",
"t c #B3B3B3",
"y c #BCBCBC",
"u c #C1C1C1",
"i c #CBCBCB",
"p c #D3D3D3",
"a c #DCDCDC",
"s c #E4E4E4",
"d c #EEEEEE",
"f c #EFF0EF",
"g c #F7F7F7",
"h c #FBFBFB",
/* pixels */
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                               d6                                                               ",
"                                                               g>                                                               ",
"                                                              gg>.                                                              ",
"                                                              gg<.                                                              ",
"                                                             ggd,.@                                                             ",
"                                                             ggd,.o                                                             ",
"                                                            gggg,.o.                                                            ",
"                                                            gggd<.o.                                                            ",
"                                                           ggggg<.o..                                                           ",
"                                                           ggggg,.o..                                                           ",
"                                                          gggggd<.o...                                                          ",
"                                                         ggggggd<.o...                                                          ",
"                                                         ggggggd<.o....                                                         ",
"                                                        gggggggd,.o.....                                                        ",
"                                                        gggggggg<.o.....                                                        ",
"                                                       ggggggggd<.o......                                                       ",
"                                                       ggggggggd<.o......                                                       ",
"                                                      gggggggggg,.o.......                                                      ",
"                                                      gggggggggd<.o.......                                                      ",
"                                                     ggggggggggg<.o........                                                     ",
"                                                     ggggggggggd,.o........                                                     ",
"                                                    gggggggggggg<.o.........                                                    ",
"                                                    gggggggggggg<.o.........                                                    ",
"                                                   ggggggggggggd<.o..........                                                   ",
"                                                   ggggggggggggg,.o..........                                                   ",
"                                                  gggggggggggggd<.o...........                                                  ",
"                                                  gggggggggggggd<.o...........                                                  ",
"                                                 ggggggggggggggg,.o............                                                 ",
"                                                 ggggggggggggggd<.o............                                                 ",
"                                                gggggggggggggggd<.o.............                                                ",
"                                                gggggggggggggggg<.o.............                                                ",
"                                               ggggggggggggggggg<.o..............                                               ",
"                                              gggggggggggggggggg<.o..............                                               ",
"                                              gggggggggggggggggg<.o...............                                              ",
"                                             ggggggggggggggggggd<.o...............X                                             ",
"                                             ggggggggggggggggggd,.o................                                             ",
"                                            gggggggggggggggggggg<.o........X........                                            ",
"                                            gggggggggggggggggggd<.o.................                                            ",
"                                           ggggggggggggggggggggd<.o..............X...                                           ",
"                                           ggggggggggggggggggggg<.@..................                                           ",
"                                          gggggggggggggggggggggd,.@..........X......X.                                          ",
"                                          gggggggggggggggggggggg<.o...................                                          ",
"                                         ggggggggggggggggggggggd<.o.X...........X..X..X                                         ",
"                                         ggggggggggggggggggggggg<.o............X....X..                                         ",
"                                        gggggggggggggggggggggggg<.@.............X.X...X.                                        ",
"                                        gggggggggggggggggggggggg<.o.......X.X..X........                                        ",
"                                       ggggggggggggggggggggggggd<.@......X.X.X...........                                       ",
"                                       ggggggggggggggggggggggggd,.@.............X.X.X.X..                                       ",
"                                      gggggggggggggggggggggggggg<.o....X......X........XX.                                      ",
"                                      gggggggggggggggggggggggggd<.o......XX..X...X.X.....X                                      ",
"                                     ggggggggggggggggggggggggggd<.@..X.X...X..X......X.XX..                                     ",
"                                    gggggggggggggggggggggggggggg<.+......X......X.X.X.X...X                                     ",
"                                    gggggggggggggggggggggggggggd<.+..X...X.X..X...X...X.X..X                                    ",
"                                   ggggggggggggggggggggggggggggg<.+....X.....X..X..XX..XX..X                                    ",
"                                   ggggggggggggggggggggggggggggd<.o...X..X..XX.X.X...X.X.X..X                                   ",
"                                  gggggggggggggggggggggggggggggg<.@........X.....XX...X.X..X.X                                  ",
"                                  gggggggggggggggggggggggggggggg<.+..X...X....X.X..XX.X..XX...                                  ",
"                                 ggggggggggggggggggggggggggggggg<.+...X.X.X.XX.X..X..X.X...XXX.                                 ",
"                                 ggggggggggggggggggggggggggggggd<.o...XX.XX.XX.X.X..X.X.X.XX.X.                                 ",
"                                gggggggggggggggggggggggggggggggd<.@.X...........X..XX..X.XX.X.XX                                ",
"                                gggggggggggggggggggggggggggggggg<.+..XX.X..X.XX.X..X..X.X..XXXX.                                ",
"                               ggggggggggggggggggggggggggggggggd<.@..X...XX.X..X.X..XX.X.XX..X.XX                               ",
"                               ggggggggggggggggggggggggggggggggd<.+.X..XX..X..X..X.X.XX.X.XX.X.XX                               ",
"                              gggggggggggggggggggggggggggggggggg<.+.X.X..X...XX.X.X.X.XXXX.XX.XXX.                              ",
"                              gggggggggggggggggggggggggggggggggd<.@...X..X.XX.X..XX..XX..XX...X..X                              ",
"                             ggggggggggggggggggggggggggggggggggd<.+.X..XX..X.X.XXX.X.XX.X..XXX.XXXX                             ",
"                             ggggggggggggggggggggggggggggggggggg<.@...X...XX.X.XX.XX.X.XXX.XX..XXXX                             ",
"                            gggggggggggggggggggggggggggggggggggd<.+.XX..XX.XX..X.XX.X.X...X.XXXX.X.X                            ",
"                            gggggggggggggggggggggggggggggggggggg<.+X.X.X.XX..XX..X.XX.XXX.XX.X.XXXXX                            ",
"                           ggggggggggggggggggggggggggggggggggggg<.+.X.XXX..XXX.XX.XX.X.XXXX.XXXXX.XXX                           ",
"                           ggggggggggggggggggggggggggggggggggggf<.@.X.X..XX...X.X.X.X..XXXX..XXX.XXXX                           ",
"                          gggggggggggggggggggggggggggggggggggggd<.+.X..XX.XXXX.XX..XXXXX.XXXXXX.XXX..X                          ",
"                         ggggggggggggggggggggggggggggggggggggggg<.+..XX.X.X..XXX.XXX.X.X.XXX.XX..X.XXX                          ",
"                         ggggggggggggggggggggggggggggggggggggggd<.@XX.XX.X.XX.X.X.X.XXXXXXX.XXXXXXXXXXX                         ",
"                        gggggggggggggggggggggggggggggggggggggggd<.+XX.X.XX.X.X.XXXX.X.XX.XX.XXXXX.XXXXX                         ",
"                        gggggggggggggggggggggggggggggggggggggggg<.+..XXX.XX..XX..XXXXX.XXXXX.X.XXXXXXXXX                        ",
"                       ggggggggggggggggggggggggggggggggggggggggd<.@.X..XX..XXX.XX.X.XXXX.X.XX.XXXXX.XXXX                        ",
"                       ggggggggggggggggggggggggggggggggggggggggd<.+..XX..XXXXXXXXXXX.X.XXXXXXXXXXXXXXXXXX                       ",
"                      gggggggggggggggggggggggggggggggggggggggggg<.+XXX.X.XXX.X.X.X.XX.XXXX.XXXXXXXX.XXXXXX                      ",
"                      gggggggggggggggggggggggggggggggggggggggggg<.+..XXXXXX.XXXXXXXXXX.X.XXXXXXXXXXXXXXXXX                      ",
"                     ggggggggggggggggggggggggggggggggggggggggggg<.@XXX.X.X.XXX.XXX.X.XXXXXXX.XXXXXXXXXXXXXX                     ",
"                     ggggggggggggggggggggggggggggggggggggggggggg<.+.X.XXXXXXX.XXX.XXXXXXXXXXXXXXXXXXXXXXXXX                     ",
"                    gggggggggggggggggggggggggggggggggggggggggggf<.@.XXXXXXX..XXXX.XXXXXXXXXXXXXXXXXXXXXXOXXX                    ",
"                    gggggggggggggggggggggggggggggggggggggggggggf<.+..X.X.XXXXXX.XXXXX.XXXXX.XXX.X.XXXXXXXXXX                    ",
"                   ggggggggggggggggggggggggggggggggggggggggggggg<.+XXXX..XXX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXOX                   ",
"                   ggggggggggggggggggggggggggggggggggggggggggggf<.@X.XXXXXX.XXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXX                   ",
"                  gggggggggggggggggggggggggggggggggggggggggggggf<.+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  ",
"                  gggggggggggggggggggggggggggggggggggggggggggggg<.+XXX.XX..XXXXXXX.XXXXXXXXXXXXXOXXXXXXXXOXXXX                  ",
"                 ggggggggggggggggggggggggggggggggggggggggggggggf<.@..X.XXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXOXXXXXXOX                 ",
"                 ggggggggggggggggggggggggggggggggggggggggggggggd<.@.XXXXXXXXX.XXXXXXXXX.XXXXXXXXXXOXXXXXXXXXXXX                 ",
"                gggggggggggggggggggggggggggggggggggggggggggggggg<.@.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOXXXXXXXXXXXO                ",
"                gggggggggggggggggggggggggggggggggggggggggggggggf<.+XX.XXXXXXXXXXXXXXXXXXXXOXXXXOXXXXXXXXXXXOXOXO                ",
"               ggggggggggggggggggggggggggggggggggggggggggggggggg<.+XXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXOXOXXXXXXX               ",
"              gggggggggggggggggggggggggggggggggggggggggggggggggg<.+XXXXXXXXXXXXXXXXXXXXXXXXXXOXXOXXXOXXXXOXOXOXOO               ",
"              gggggggggggggggggggggggggggggggggggggggggggggggggf<.@..XXXXXXXXXXXXXXXXXXOXXXXOXXXXXXXXXXXXXOXOXXXXX              ",
"             ggggggggggggggggggggggggggggggggggggggggggggggggggd<.@XXXXXXXXXXXXXXXXXXXXXOXXXXXXXXXXOXOXOOXXXXXOXOX              ",
"             ggggggggggggggggggggggggggggggggggggggggggggggggggg<.+XXXXXX.XXXXXXXXXXXXXXXXXXXXXXOXXXXOXXXXOXXXXOXOX             ",
"            gggggggggggggggggggggggggggggggggggggggggggggggggggf<.+XXXXXXXXXXXXXXXOXOXXXXXOXXXXOOXOXXXXOOXXXXOXOXXO             ",
"            gggggggggggggggggggggggggggggggggggggggggggggggggggg<.+XXXXXXXXXXXOXXXOXXXXXXXXXXXXXXOXXXOXXXXXXXXXXXXOX            ",
"           ggggggggggggggggggggggggggggggggggggggggggggggggggggg<.@oXXXXXXXXXXXXXXXXXXXXXXXOXOOXXXOXXXXOXOXOOXOXOOXOX           ",
"           ggggggggggggggggggggggggggggggggggggggggggggggggggggd<....X+OXXXXXXXXOXXXXXOXXXXOXXXXOXXXXOXXXXXOXXXOXOOXO           ",
"          ggggggggggggggggggggggggggggggggggggggggggggggggggsir963<;+...XOoXOXXXXXXXXXXXOXXXXOOXXXXOXOXOXOXXOXOXOXXXOX          ",
"          ggggggggggggggggggggggggggggggggggggggggggggggdpt06556776652<*X...XoXXXXXXOOXXOXXXOXOXXXXOXXXXOXXOXOXOXXOXOX          ",
"         ggggggggggggggggggggggggggggggggggggggggggggayq866678776666666531>$....X+OXXXOXXXXOXXXXXOXOOXXOXOOXXXOXOXXOXOO         ",
"         ggggggggggggggggggggggggggggggggggggggggaue9768888877777666655555532<:$....XXOXXXXXXOOXXXXXXXOXOXXOOXOXXXOXOXO         ",
"        gggggggggggggggggggggggggggggggggggggair087889988887777776666655555444331,=#...XOOOOXXXXOXOXOXXOXOOXXOXOOOXOXXOX        ",
"        gggggggggggggggggggggggggggggggggsirq989900998988887777766666555553333323322<>*+....XXoXXXOXXOOXXOXOXOXOXOXOXOXO        ",
"       ggggggggggggggggggggggggggggggdpte09900000999998888887777766665655353533322222211,:&X...XOOXOOXXOOXOXXXOXOXOXOOOOX       ",
"       ggggggggggggggggggggggggggdpyeq00qqqq00009999988887777776766665555355333232221121111<>=$X..XXOOOXXOOXOXXOXOXOOXXOO       ",
"      gggggggggggggggggggggggdairwqqqwwqqq0q000009998998888877766666665555333333222221111<1<<<<,:*#X..XXOXXOXOXOOOXOXOOOOX      ",
"      gggggggggggggggggggdaitewwwewwwqwqqqq00009999998988887777766666565545333323222211111<<<<<,,<>:=%+XXXXOXOXOXOXOOXOXXO      ",
"     gggggggggggggggggspyreweeeewewwwwqqq0q000090999988887877777676665555544333322222211<11<<<,,>>>>>::-&#+XXXOXXOOOOOXOOOX     ",
"     gggggggggggggsautrererreeeewwwwqwqqqq00000009999888878777777666665554433323322111111<<<<<,,>>>>:>::::-*&@XXXOOXXXOOOXO     ",
"    ggggggggggdapyrrtrrtrrereeewwwwwwqqqqqq0q0099999989888877767666655555443333222222221111<<<<,>>>>>::::-:====&$+OXXOOXXOOO    ",
"   gggggggdsiutttttttrrrrrreeeewewwwwqqqqqq0000099998988887777766666655544333333222221111<1<<<<,<>>>>::::;;===***&%$@+XXOXXO    ",
"   ggggdpiuyyuuyyyyytytttrrrrrreeeewwwwwqqqqqq0000099989888878777766665656555333332222121111<<<<<>>>>::>:;;=;===*&&&%&$#+OOOO   ",
"   gaiuyyuuuyyyyttttttrrrrereeewwwwwwqwqqq0q000990999988888777776666655545433323222221111<<<<<<>>>>>:>::::;;===&*%&&%$%$$$@+O   ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                "
};

static Fl_Pixmap gmsh_icon_pixmap(gmsh_icon_xpm);

#endif
