# CMake generated Testfile for 
# Source directory: /home/hillewaert/srcs/gmsh_git
# Build directory: /home/hillewaert/srcs/gmsh_git/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(../tutorial/t1.geo "./gmsh" "../tutorial/t1.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t10.geo "./gmsh" "../tutorial/t10.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t11.geo "./gmsh" "../tutorial/t11.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t12.geo "./gmsh" "../tutorial/t12.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t13.geo "./gmsh" "../tutorial/t13.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t14.geo "./gmsh" "../tutorial/t14.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t15.geo "./gmsh" "../tutorial/t15.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t16.geo "./gmsh" "../tutorial/t16.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t17.geo "./gmsh" "../tutorial/t17.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t2.geo "./gmsh" "../tutorial/t2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t3.geo "./gmsh" "../tutorial/t3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t4.geo "./gmsh" "../tutorial/t4.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t5.geo "./gmsh" "../tutorial/t5.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t6.geo "./gmsh" "../tutorial/t6.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t7.geo "./gmsh" "../tutorial/t7.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t8.geo "./gmsh" "../tutorial/t8.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../tutorial/t9.geo "./gmsh" "../tutorial/t9.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/post_processing/lowmem-anim.geo "./gmsh" "../demos/post_processing/lowmem-anim.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/post_processing/plot2d.geo "./gmsh" "../demos/post_processing/plot2d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/post_processing/view_groups.geo "./gmsh" "../demos/post_processing/view_groups.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/antenna.geo "./gmsh" "../demos/simple_geo/antenna.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/component8_in_a_box.geo "./gmsh" "../demos/simple_geo/component8_in_a_box.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/cone.geo "./gmsh" "../demos/simple_geo/cone.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/cube.geo "./gmsh" "../demos/simple_geo/cube.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/fields.geo "./gmsh" "../demos/simple_geo/fields.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/filter.geo "./gmsh" "../demos/simple_geo/filter.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/hex.geo "./gmsh" "../demos/simple_geo/hex.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/homology.geo "./gmsh" "../demos/simple_geo/homology.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/indheat.geo "./gmsh" "../demos/simple_geo/indheat.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/machine.geo "./gmsh" "../demos/simple_geo/machine.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/piece-extr-rec.geo "./gmsh" "../demos/simple_geo/piece-extr-rec.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/piece-extr.geo "./gmsh" "../demos/simple_geo/piece-extr.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/piece.geo "./gmsh" "../demos/simple_geo/piece.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/pripyrtet.geo "./gmsh" "../demos/simple_geo/pripyrtet.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/sphere-discrete.geo "./gmsh" "../demos/simple_geo/sphere-discrete.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/sphere.geo "./gmsh" "../demos/simple_geo/sphere.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/splines.geo "./gmsh" "../demos/simple_geo/splines.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/square_regular.geo "./gmsh" "../demos/simple_geo/square_regular.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/tower.geo "./gmsh" "../demos/simple_geo/tower.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/simple_geo/transfinite.geo "./gmsh" "../demos/simple_geo/transfinite.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/struct/Exists_GetForced.geo "./gmsh" "../demos/struct/Exists_GetForced.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../demos/struct/struct.geo "./gmsh" "../demos/struct/struct.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/1d/ellipses.geo "./gmsh" "../benchmarks/1d/ellipses.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/1d/ligne.geo "./gmsh" "../benchmarks/1d/ligne.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/1d/nurbs.geo "./gmsh" "../benchmarks/1d/nurbs.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/1d/periodic_bspline.geo "./gmsh" "../benchmarks/1d/periodic_bspline.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/1d/periodic_spline.geo "./gmsh" "../benchmarks/1d/periodic_spline.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/1d/progression.geo "./gmsh" "../benchmarks/1d/progression.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/BL0.geo "./gmsh" "../benchmarks/2d/BL0.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/BL1.geo "./gmsh" "../benchmarks/2d/BL1.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/BL2.geo "./gmsh" "../benchmarks/2d/BL2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/BL3.geo "./gmsh" "../benchmarks/2d/BL3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/IPE.geo "./gmsh" "../benchmarks/2d/IPE.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/ReplaceDuplicatePoints_Bug.geo "./gmsh" "../benchmarks/2d/ReplaceDuplicatePoints_Bug.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/SFR.geo "./gmsh" "../benchmarks/2d/SFR.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/Square-01.geo "./gmsh" "../benchmarks/2d/Square-01.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/Square-02.geo "./gmsh" "../benchmarks/2d/Square-02.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/Square-Attr1.geo "./gmsh" "../benchmarks/2d/Square-Attr1.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/Square-Attr2.geo "./gmsh" "../benchmarks/2d/Square-Attr2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/Square-Attr3.geo "./gmsh" "../benchmarks/2d/Square-Attr3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/Square-Attr4.geo "./gmsh" "../benchmarks/2d/Square-Attr4.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/Square-Emb.geo "./gmsh" "../benchmarks/2d/Square-Emb.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/TieAnchor520.geo "./gmsh" "../benchmarks/2d/TieAnchor520.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/bad_ruled_example.geo "./gmsh" "../benchmarks/2d/bad_ruled_example.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/bounding_box_pb.geo "./gmsh" "../benchmarks/2d/bounding_box_pb.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/brombo.geo "./gmsh" "../benchmarks/2d/brombo.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/brombo2.geo "./gmsh" "../benchmarks/2d/brombo2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/coin.geo "./gmsh" "../benchmarks/2d/coin.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/compound.geo "./gmsh" "../benchmarks/2d/compound.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/conge.geo "./gmsh" "../benchmarks/2d/conge.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/contact2d.geo "./gmsh" "../benchmarks/2d/contact2d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/copy_mesh_spec_with_duplicata.geo "./gmsh" "../benchmarks/2d/copy_mesh_spec_with_duplicata.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/disk_sym.geo "./gmsh" "../benchmarks/2d/disk_sym.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/double_attractor.geo "./gmsh" "../benchmarks/2d/double_attractor.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/elliptic.geo "./gmsh" "../benchmarks/2d/elliptic.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/embedded_points.geo "./gmsh" "../benchmarks/2d/embedded_points.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/embedded_recombine.geo "./gmsh" "../benchmarks/2d/embedded_recombine.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/field_nico.geo "./gmsh" "../benchmarks/2d/field_nico.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/field_restrict.geo "./gmsh" "../benchmarks/2d/field_restrict.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/fissure.geo "./gmsh" "../benchmarks/2d/fissure.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/foil_bernhard.geo "./gmsh" "../benchmarks/2d/foil_bernhard.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/function.geo "./gmsh" "../benchmarks/2d/function.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/function_field.geo "./gmsh" "../benchmarks/2d/function_field.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/fx79.geo "./gmsh" "../benchmarks/2d/fx79.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/fx79w151a.geo "./gmsh" "../benchmarks/2d/fx79w151a.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/hybrid_compound.geo "./gmsh" "../benchmarks/2d/hybrid_compound.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/hybrid_discrete.geo "./gmsh" "../benchmarks/2d/hybrid_discrete.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/intersect.geo "./gmsh" "../benchmarks/2d/intersect.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/line_in_surface.geo "./gmsh" "../benchmarks/2d/line_in_surface.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/machine/Machine.geo "./gmsh" "../benchmarks/2d/machine/Machine.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/machine2/Machine.geo "./gmsh" "../benchmarks/2d/machine2/Machine.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/machine3/Machine.geo "./gmsh" "../benchmarks/2d/machine3/Machine.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/many_holes.geo "./gmsh" "../benchmarks/2d/many_holes.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/mean.geo "./gmsh" "../benchmarks/2d/mean.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/naca12BL.geo "./gmsh" "../benchmarks/2d/naca12BL.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/naca12_2d.geo "./gmsh" "../benchmarks/2d/naca12_2d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/naca12_2d_trailing.geo "./gmsh" "../benchmarks/2d/naca12_2d_trailing.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/needs_rand_1e-9.geo "./gmsh" "../benchmarks/2d/needs_rand_1e-9.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/nested_tramsforms.geo "./gmsh" "../benchmarks/2d/nested_tramsforms.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/periodic_affine.geo "./gmsh" "../benchmarks/2d/periodic_affine.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/periodic_bspline.geo "./gmsh" "../benchmarks/2d/periodic_bspline.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/periodic_rotation_on_axis.geo "./gmsh" "../benchmarks/2d/periodic_rotation_on_axis.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/predator.geo "./gmsh" "../benchmarks/2d/predator.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/projection.geo "./gmsh" "../benchmarks/2d/projection.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/raccord.geo "./gmsh" "../benchmarks/2d/raccord.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/recombine.geo "./gmsh" "../benchmarks/2d/recombine.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/ruled_on_sphere.geo "./gmsh" "../benchmarks/2d/ruled_on_sphere.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/runner_simple_2d.geo "./gmsh" "../benchmarks/2d/runner_simple_2d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/slot.geo "./gmsh" "../benchmarks/2d/slot.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/sphere_transfinite.geo "./gmsh" "../benchmarks/2d/sphere_transfinite.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/spherehole.geo "./gmsh" "../benchmarks/2d/spherehole.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/spline.geo "./gmsh" "../benchmarks/2d/spline.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/square.geo "./gmsh" "../benchmarks/2d/square.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/stator_parametric.geo "./gmsh" "../benchmarks/2d/stator_parametric.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/thin.geo "./gmsh" "../benchmarks/2d/thin.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/transf_complex.geo "./gmsh" "../benchmarks/2d/transf_complex.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/transfinite.geo "./gmsh" "../benchmarks/2d/transfinite.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/transfinite_b.geo "./gmsh" "../benchmarks/2d/transfinite_b.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/transfinite_coherence.geo "./gmsh" "../benchmarks/2d/transfinite_coherence.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/transfinite_tri_ugly_fix.geo "./gmsh" "../benchmarks/2d/transfinite_tri_ugly_fix.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/transfo_neg_curves.geo "./gmsh" "../benchmarks/2d/transfo_neg_curves.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/transformador.geo "./gmsh" "../benchmarks/2d/transformador.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/tresse.geo "./gmsh" "../benchmarks/2d/tresse.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/tresse2.geo "./gmsh" "../benchmarks/2d/tresse2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/tresse3.geo "./gmsh" "../benchmarks/2d/tresse3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/wing.geo "./gmsh" "../benchmarks/2d/wing.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/world.geo "./gmsh" "../benchmarks/2d/world.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/2d/xytouv.geo "./gmsh" "../benchmarks/2d/xytouv.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/2spheres.geo "./gmsh" "../benchmarks/3d/2spheres.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/CoilAboveACrack.geo "./gmsh" "../benchmarks/3d/CoilAboveACrack.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Cube-01.geo "./gmsh" "../benchmarks/3d/Cube-01.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Cube-02.geo "./gmsh" "../benchmarks/3d/Cube-02.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Cube-03.geo "./gmsh" "../benchmarks/3d/Cube-03.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Cube-04.geo "./gmsh" "../benchmarks/3d/Cube-04.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Cube-05.geo "./gmsh" "../benchmarks/3d/Cube-05.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Cube-06.geo "./gmsh" "../benchmarks/3d/Cube-06.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Cube-07.geo "./gmsh" "../benchmarks/3d/Cube-07.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Cube-08.geo "./gmsh" "../benchmarks/3d/Cube-08.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Cube-Attr-01.geo "./gmsh" "../benchmarks/3d/Cube-Attr-01.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Cube-Attr-02.geo "./gmsh" "../benchmarks/3d/Cube-Attr-02.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Cube-Attr-03.geo "./gmsh" "../benchmarks/3d/Cube-Attr-03.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/CubeAniso2.geo "./gmsh" "../benchmarks/3d/CubeAniso2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/CubeFullPeriodic.geo "./gmsh" "../benchmarks/3d/CubeFullPeriodic.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/CubePeriodic.geo "./gmsh" "../benchmarks/3d/CubePeriodic.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/PHX.geo "./gmsh" "../benchmarks/3d/PHX.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/PeriodicRotationAndTranslation.geo "./gmsh" "../benchmarks/3d/PeriodicRotationAndTranslation.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Revolve.geo "./gmsh" "../benchmarks/3d/Revolve.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Revolve2.geo "./gmsh" "../benchmarks/3d/Revolve2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Revolve3.geo "./gmsh" "../benchmarks/3d/Revolve3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Sphere.geo "./gmsh" "../benchmarks/3d/Sphere.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Torus.geo "./gmsh" "../benchmarks/3d/Torus.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Torus2.geo "./gmsh" "../benchmarks/3d/Torus2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/TwoCloseVolumes.geo "./gmsh" "../benchmarks/3d/TwoCloseVolumes.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/Xpopo.geo "./gmsh" "../benchmarks/3d/Xpopo.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/bicrystal-degre2.geo "./gmsh" "../benchmarks/3d/bicrystal-degre2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/biglc.geo "./gmsh" "../benchmarks/3d/biglc.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/brain.geo "./gmsh" "../benchmarks/3d/brain.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/bug_prot.geo "./gmsh" "../benchmarks/3d/bug_prot.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/calbute.geo "./gmsh" "../benchmarks/3d/calbute.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/cas_pb.geo "./gmsh" "../benchmarks/3d/cas_pb.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/cea.geo "./gmsh" "../benchmarks/3d/cea.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/cellbody.geo "./gmsh" "../benchmarks/3d/cellbody.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/coil_crack/Piece1_4z1b.geo "./gmsh" "../benchmarks/3d/coil_crack/Piece1_4z1b.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/coin.geo "./gmsh" "../benchmarks/3d/coin.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/concentric_sphere.geo "./gmsh" "../benchmarks/3d/concentric_sphere.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/contact3d.geo "./gmsh" "../benchmarks/3d/contact3d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/core_coil.geo "./gmsh" "../benchmarks/3d/core_coil.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/crux.geo "./gmsh" "../benchmarks/3d/crux.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/durufle.geo "./gmsh" "../benchmarks/3d/durufle.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/eddyblade3d-1.geo "./gmsh" "../benchmarks/3d/eddyblade3d-1.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/edf/Electrode_8.geo "./gmsh" "../benchmarks/3d/edf/Electrode_8.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/edf/Four.geo "./gmsh" "../benchmarks/3d/edf/Four.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/edf/Param_test.geo "./gmsh" "../benchmarks/3d/edf/Param_test.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/ellipsis.geo "./gmsh" "../benchmarks/3d/ellipsis.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/escaliers.geo "./gmsh" "../benchmarks/3d/escaliers.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/extrude_translate.geo "./gmsh" "../benchmarks/3d/extrude_translate.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/fil.geo "./gmsh" "../benchmarks/3d/fil.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/fire2_3d.geo "./gmsh" "../benchmarks/3d/fire2_3d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/francois.geo "./gmsh" "../benchmarks/3d/francois.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/function_field.geo "./gmsh" "../benchmarks/3d/function_field.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/geom8du.geo "./gmsh" "../benchmarks/3d/geom8du.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/hex.geo "./gmsh" "../benchmarks/3d/hex.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/hexaprism.geo "./gmsh" "../benchmarks/3d/hexaprism.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/hole.geo "./gmsh" "../benchmarks/3d/hole.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/inducteur_cenaero.geo "./gmsh" "../benchmarks/3d/inducteur_cenaero.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/induction1.geo "./gmsh" "../benchmarks/3d/induction1.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/induction2.geo "./gmsh" "../benchmarks/3d/induction2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/induction3.geo "./gmsh" "../benchmarks/3d/induction3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/induction4.geo "./gmsh" "../benchmarks/3d/induction4.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/lam3d_shell2_indxz.geo "./gmsh" "../benchmarks/3d/lam3d_shell2_indxz.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/mem3D_wv2.geo "./gmsh" "../benchmarks/3d/mem3D_wv2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/naca0012.geo "./gmsh" "../benchmarks/3d/naca0012.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/naca12.geo "./gmsh" "../benchmarks/3d/naca12.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/p19.geo "./gmsh" "../benchmarks/3d/p19.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/p20.geo "./gmsh" "../benchmarks/3d/p20.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/p4a.geo "./gmsh" "../benchmarks/3d/p4a.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/pb_thin_structs.geo "./gmsh" "../benchmarks/3d/pb_thin_structs.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/peca01_mod2.geo "./gmsh" "../benchmarks/3d/peca01_mod2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/peca01_mod3.geo "./gmsh" "../benchmarks/3d/peca01_mod3.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/percolation.geo "./gmsh" "../benchmarks/3d/percolation.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/perforated1.geo "./gmsh" "../benchmarks/3d/perforated1.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/periodic.geo "./gmsh" "../benchmarks/3d/periodic.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/periodic_unstructured.geo "./gmsh" "../benchmarks/3d/periodic_unstructured.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/piece_explicit_volume.geo "./gmsh" "../benchmarks/3d/piece_explicit_volume.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/plate.geo "./gmsh" "../benchmarks/3d/plate.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/prism.geo "./gmsh" "../benchmarks/3d/prism.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/raidisseur.geo "./gmsh" "../benchmarks/3d/raidisseur.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/runner_simple_3d.geo "./gmsh" "../benchmarks/3d/runner_simple_3d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/shoulder.geo "./gmsh" "../benchmarks/3d/shoulder.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/snake.geo "./gmsh" "../benchmarks/3d/snake.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/sph.geo "./gmsh" "../benchmarks/3d/sph.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/sph2.geo "./gmsh" "../benchmarks/3d/sph2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/sphere_hexa.geo "./gmsh" "../benchmarks/3d/sphere_hexa.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/sphere_horrible.geo "./gmsh" "../benchmarks/3d/sphere_horrible.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/sphere_in_cube.geo "./gmsh" "../benchmarks/3d/sphere_in_cube.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/sphere_in_cube_hexa.geo "./gmsh" "../benchmarks/3d/sphere_in_cube_hexa.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/sphere_in_sphere_hexa.geo "./gmsh" "../benchmarks/3d/sphere_in_sphere_hexa.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/sphere_layer_netgen.geo "./gmsh" "../benchmarks/3d/sphere_layer_netgen.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/sphere_with_hole.geo "./gmsh" "../benchmarks/3d/sphere_with_hole.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/spline_gmsh.geo "./gmsh" "../benchmarks/3d/spline_gmsh.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/stator1910.geo "./gmsh" "../benchmarks/3d/stator1910.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/surface3113.geo "./gmsh" "../benchmarks/3d/surface3113.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/takeit_vol.geo "./gmsh" "../benchmarks/3d/takeit_vol.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/tet.geo "./gmsh" "../benchmarks/3d/tet.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/torsion3d.geo "./gmsh" "../benchmarks/3d/torsion3d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/transfinite.geo "./gmsh" "../benchmarks/3d/transfinite.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/transfinite_auto.geo "./gmsh" "../benchmarks/3d/transfinite_auto.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/transfinite_extrude.geo "./gmsh" "../benchmarks/3d/transfinite_extrude.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/trav33D.geo "./gmsh" "../benchmarks/3d/trav33D.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/twin_ap_3D_X5.geo "./gmsh" "../benchmarks/3d/twin_ap_3D_X5.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/unit-cube.geo "./gmsh" "../benchmarks/3d/unit-cube.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/unit-cube_merge_translate_bug.geo "./gmsh" "../benchmarks/3d/unit-cube_merge_translate_bug.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/vulp5.geo "./gmsh" "../benchmarks/3d/vulp5.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/3d/warning_half_circle.geo "./gmsh" "../benchmarks/3d/warning_half_circle.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Cube-01-ExtrMesh.geo "./gmsh" "../benchmarks/extrude/Cube-01-ExtrMesh.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Cube-02-ExtrMesh.geo "./gmsh" "../benchmarks/extrude/Cube-02-ExtrMesh.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Cube-05-ExtrMesh.geo "./gmsh" "../benchmarks/extrude/Cube-05-ExtrMesh.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Cube-06-ExtrMesh.geo "./gmsh" "../benchmarks/extrude/Cube-06-ExtrMesh.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Cylinder.geo "./gmsh" "../benchmarks/extrude/Cylinder.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Forma_3DCube.geo "./gmsh" "../benchmarks/extrude/Forma_3DCube.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Process_FSWLocal.geo "./gmsh" "../benchmarks/extrude/Process_FSWLocal.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Ring_Extrude.geo "./gmsh" "../benchmarks/extrude/Ring_Extrude.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Ring_Transfinite.geo "./gmsh" "../benchmarks/extrude/Ring_Transfinite.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Test_Extrude.geo "./gmsh" "../benchmarks/extrude/Test_Extrude.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Torus-ExtrMesh-2.geo "./gmsh" "../benchmarks/extrude/Torus-ExtrMesh-2.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/Torus-ExtrMesh.geo "./gmsh" "../benchmarks/extrude/Torus-ExtrMesh.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/afpm.geo "./gmsh" "../benchmarks/extrude/afpm.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/aorta.geo "./gmsh" "../benchmarks/extrude/aorta.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/aorta_extrude.geo "./gmsh" "../benchmarks/extrude/aorta_extrude.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/biconv9-4-30-dat.geo "./gmsh" "../benchmarks/extrude/biconv9-4-30-dat.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/carve_hole.geo "./gmsh" "../benchmarks/extrude/carve_hole.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/circle_boundary_layer.geo "./gmsh" "../benchmarks/extrude/circle_boundary_layer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/cube.geo "./gmsh" "../benchmarks/extrude/cube.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/cylinder_double_boundary_layer.geo "./gmsh" "../benchmarks/extrude/cylinder_double_boundary_layer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/cylinder_wiki.geo "./gmsh" "../benchmarks/extrude/cylinder_wiki.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/degenerate.geo "./gmsh" "../benchmarks/extrude/degenerate.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/double_boundary_layer_2d.geo "./gmsh" "../benchmarks/extrude/double_boundary_layer_2d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/double_boundary_layer_3d.geo "./gmsh" "../benchmarks/extrude/double_boundary_layer_3d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/duct_boundary_layer.geo "./gmsh" "../benchmarks/extrude/duct_boundary_layer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/exact_extrusion_bug.geo "./gmsh" "../benchmarks/extrude/exact_extrusion_bug.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/flexible_transfinite.geo "./gmsh" "../benchmarks/extrude/flexible_transfinite.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/full_hex_simple.geo "./gmsh" "../benchmarks/extrude/full_hex_simple.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/hybrid.geo "./gmsh" "../benchmarks/extrude/hybrid.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/jonas.geo "./gmsh" "../benchmarks/extrude/jonas.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/m91acou4a.geo "./gmsh" "../benchmarks/extrude/m91acou4a.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/naca12_3d.geo "./gmsh" "../benchmarks/extrude/naca12_3d.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/old_extrude.geo "./gmsh" "../benchmarks/extrude/old_extrude.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/old_extrude_discrete.geo "./gmsh" "../benchmarks/extrude/old_extrude_discrete.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/onde-rec.geo "./gmsh" "../benchmarks/extrude/onde-rec.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/p7-ExtrMesh.geo "./gmsh" "../benchmarks/extrude/p7-ExtrMesh.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/piece-extr.geo "./gmsh" "../benchmarks/extrude/piece-extr.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/point.geo "./gmsh" "../benchmarks/extrude/point.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/point_new.geo "./gmsh" "../benchmarks/extrude/point_new.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/rail.geo "./gmsh" "../benchmarks/extrude/rail.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/runner_simple_3d-ExtrMesh.geo "./gmsh" "../benchmarks/extrude/runner_simple_3d-ExtrMesh.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/sphere_boundary_layer.geo "./gmsh" "../benchmarks/extrude/sphere_boundary_layer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/sphere_boundary_layer_from_view.geo "./gmsh" "../benchmarks/extrude/sphere_boundary_layer_from_view.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/sphere_discrete.geo "./gmsh" "../benchmarks/extrude/sphere_discrete.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/sphere_double_boundary_layer.geo "./gmsh" "../benchmarks/extrude/sphere_double_boundary_layer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/spirale.geo "./gmsh" "../benchmarks/extrude/spirale.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/stator-newxtr.geo "./gmsh" "../benchmarks/extrude/stator-newxtr.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/stator-oldxtr.geo "./gmsh" "../benchmarks/extrude/stator-oldxtr.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/stator1910.geo "./gmsh" "../benchmarks/extrude/stator1910.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/t1_boundary_layer.geo "./gmsh" "../benchmarks/extrude/t1_boundary_layer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/t1_boundary_layer_connection.geo "./gmsh" "../benchmarks/extrude/t1_boundary_layer_connection.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/test8.geo "./gmsh" "../benchmarks/extrude/test8.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/thin.geo "./gmsh" "../benchmarks/extrude/thin.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/torus_hexa.geo "./gmsh" "../benchmarks/extrude/torus_hexa.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/tunnel_simpler.geo "./gmsh" "../benchmarks/extrude/tunnel_simpler.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/tycoelectronics.geo "./gmsh" "../benchmarks/extrude/tycoelectronics.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/u_shape_boundary_layer.geo "./gmsh" "../benchmarks/extrude/u_shape_boundary_layer.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/vertex_search_problem.geo "./gmsh" "../benchmarks/extrude/vertex_search_problem.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/vianew-rec.geo "./gmsh" "../benchmarks/extrude/vianew-rec.geo" "-3" "-nopopup" "-o" "./tmp.msh")
add_test(../benchmarks/extrude/vianew.geo "./gmsh" "../benchmarks/extrude/vianew.geo" "-3" "-nopopup" "-o" "./tmp.msh")
subdirs("Common")
subdirs("Numeric")
subdirs("Geo")
subdirs("Mesh")
subdirs("Solver")
subdirs("Post")
subdirs("Plugin")
subdirs("Parser")
subdirs("Fltk")
subdirs("contrib/onelab")
subdirs("contrib/mpeg_encode")
subdirs("Graphics")
subdirs("contrib/ANN")
subdirs("contrib/lbfgs")
subdirs("contrib/DiscreteIntegration")
subdirs("contrib/HighOrderMeshOptimizer")
subdirs("contrib/MeshOptimizer")
subdirs("contrib/MeshQualityOptimizer")
subdirs("contrib/kbipack")
subdirs("contrib/MathEx")
subdirs("contrib/Metis")
subdirs("contrib/Chaco")
subdirs("contrib/voro++")
subdirs("contrib/blossom")
subdirs("contrib/Netgen")
subdirs("contrib/bamg")
subdirs("contrib/mmg3d")
subdirs("contrib/Tetgen1.5")
subdirs("contrib/taucs")
