#
# Makefile for geometric library
#
src = stlgeom.cpp stltopology.cpp stlgeomchart.cpp stlgeommesh.cpp meshstlsurface.cpp stlline.cpp stltool.cpp
#
lib = stlgeom
libpath = libsrc/stlgeom 
#
#
include ../makefile.inc
#
