# Make the fonts Gmsh draws its strings with when it has no window (see
# src/graphics/stbStrings.cpp): subsets of the Liberation fonts 2.x, renamed as
# the SIL Open Font License asks of modified versions (Liberation, Arimo, Tinos
# and Cousine are reserved font names), written as C arrays in fonts.h.
#
# Usage: python3 make_fonts.py <directory of the Liberation .ttf files>
# (e.g. /usr/share/fonts/truetype/liberation on Debian); needs fontTools.

import io
import os
import sys

from fontTools import subset
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.ttLib import TTFont

# Latin-1, Greek (with the variants the Symbol font has), and the punctuation
# and mathematical signs a label may hold
CODES = (list(range(0x20, 0x7f)) + list(range(0xa0, 0x100)) +
         list(range(0x391, 0x3aa)) + list(range(0x3b1, 0x3ca)) +
         [0x3d1, 0x3d5, 0x3d6, 0x203e] + [
             0x2013, 0x2014, 0x2018, 0x2019, 0x201c, 0x201d, 0x2022, 0x2026,
             0x2032, 0x2033, 0x2070, 0x2074, 0x2075, 0x2076, 0x2077, 0x2078,
             0x2079, 0x207a, 0x207b, 0x2080, 0x2081, 0x2082, 0x2083, 0x2084,
             0x2085, 0x2086, 0x2087, 0x2088, 0x2089, 0x2190, 0x2191, 0x2192,
             0x2193, 0x2202, 0x2206, 0x2207, 0x220f, 0x2211, 0x2212, 0x221a,
             0x221e, 0x222b, 0x2248, 0x2260, 0x2261, 0x2264, 0x2265
         ])

FAMILIES = [('Sans', 'Sans'), ('Serif', 'Serif'), ('Mono', 'Mono')]
STYLES = [('Regular', 'Regular'), ('Bold', 'Bold'), ('Italic', 'Italic'),
          ('BoldItalic', 'Bold Italic')]


# superscripts the fonts lack (Gmsh writes the powers of ten of its scales
# with them), and the character each is drawn from
SUPERSCRIPTS = {0x2070: 0x30, 0x207a: 0x2b, 0x207b: 0x2212}


def add_superscripts(font):
    # drawn as the font draws its superscript four from its four: scaled and
    # moved the same way, with the same advance; the signs centred on it
    cmap = font.getBestCmap()
    if 0x2074 not in cmap or 0x34 not in cmap:
        return
    glyf, hmtx = font['glyf'], font['hmtx']

    def box(name):
        g = glyf[name]
        g.recalcBounds(glyf)
        return g.xMin, g.yMin, g.xMax, g.yMax

    four, sup = box(cmap[0x34]), box(cmap[0x2074])
    scale = (sup[3] - sup[1]) / float(four[3] - four[1])
    advance = hmtx[cmap[0x2074]][0]
    glyphs = font.getGlyphSet()
    for code, base in SUPERSCRIPTS.items():
        if code in cmap or base not in cmap:
            continue
        b = box(cmap[base])
        if base == 0x30:
            dx = sup[0] - scale * four[0]
            dy = sup[1] - scale * four[1]
        else:
            dx = (advance - scale * (b[0] + b[2])) / 2.
            dy = (sup[1] + sup[3]) / 2. - scale * (b[1] + b[3]) / 2.
        pen = TTGlyphPen(glyphs)
        glyphs[cmap[base]].draw(
            TransformPen(pen, (scale, 0, 0, scale, round(dx), round(dy))))
        name = 'uni%04X' % code
        glyf[name] = pen.glyph()
        glyf[name].recalcBounds(glyf)
        hmtx[name] = (advance, glyf[name].xMin)
        for table in font['cmap'].tables:
            if table.isUnicode():
                table.cmap[code] = name


def make(path, family, style):
    font = TTFont(path)
    add_superscripts(font)
    options = subset.Options()
    options.hinting = False
    options.layout_features = ['kern']
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
    options.notdef_outline = True
    sub = subset.Subsetter(options)
    sub.populate(unicodes=CODES)
    sub.subset(font)
    # the reserved names are not to be used by a modified version
    name = 'Gmsh ' + family
    names = {1: name, 3: name + ' ' + style[1] + ' (subset of Liberation ' +
             family + ' 2)', 4: name + ' ' + style[1],
             6: 'Gmsh' + family + '-' + style[0]}
    table = font['name']
    for n in table.names:
        if n.nameID in names:
            n.string = names[n.nameID]
    out = io.BytesIO()
    font.save(out)
    return out.getvalue()


def main():
    src = sys.argv[1]
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, 'fonts.h'), 'w') as f:
        f.write('// Generated by make_fonts.py: subsets of the Liberation '
                'fonts 2.x, under the\n// SIL Open Font License 1.1 (see '
                'OFL.txt), renamed Gmsh Sans, Gmsh Serif and\n// Gmsh Mono. '
                'Do not edit.\n\n')
        for family, _ in FAMILIES:
            for style in STYLES:
                data = make(os.path.join(src, 'Liberation%s-%s.ttf' %
                                         (family, style[0])), family, style)
                var = 'gmsh%s%s' % (family, style[0])
                f.write('static const unsigned char %s[%d] = {\n' %
                        (var, len(data)))
                for i in range(0, len(data), 16):
                    f.write('  ' + ','.join('%d' % b for b in data[i:i + 16]) +
                            ',\n')
                f.write('};\n\n')
                print(var, len(data))


if __name__ == '__main__':
    main()
