#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "v6.2.2608"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2608
#define NETGEN_VERSION_TWEAK 0
#define NETGEN_VERSION_HASH "96e5682"
#endif
