#ifndef NETGEN_CONFIG_HPP_INCLUDED___
#define NETGEN_CONFIG_HPP_INCLUDED___
#define NETGEN_USE_NATIVE_ARCH 0
#define NETGEN_USE_GUI 0
#define NETGEN_USE_PYTHON 0
#define NETGEN_USE_MPI 0
#define NETGEN_USE_MPI4PY 0
#define NETGEN_USE_OCC 0
#define NETGEN_USE_JPEG 0
#define NETGEN_USE_MPEG 0
#define NETGEN_USE_CGNS 0
#define NETGEN_USE_NUMA 0
#define NETGEN_INTEL_MIC 0
#define NETGEN_INSTALL_PROFILES 0
#define NETGEN_USE_CCACHE 0
#define NETGEN_USE_INTERNAL_TCL 0
#define NETGEN_ENABLE_UNIT_TESTS 0
#define NETGEN_ENABLE_CPP_CORE_GUIDELINES_CHECK 0
#define NETGEN_USE_SPDLOG 0
#define NETGEN_DEBUG_LOG 0
#define NETGEN_USE_CHECK_RANGE 0
#define NETGEN_POINTINDEX_BASE 1
#define NETGEN_BUILD_STUB_FILES 0
#define NETGEN_BUILD_FOR_CONDA 0
#define NETGEN_SHARED_LIBRARY_SUFFIX ".so"
#endif
