# MODIFIED FOR GMSH
#src = nginterface.cpp writeuser.cpp writediffpack.cpp writeabaqus.cpp writefluent.cpp writepermas.cpp writetochnog.cpp writetecplot.cpp wuchemnitz.cpp writetochnog.cpp writefeap.cpp writeelmer.cpp  writegmsh.cpp writejcm.cpp writetet.cpp writedolfin.cpp readuser.cpp importsolution.cpp readtetmesh.cpp
src = nglib.cpp
#
lib = nginterface
libpath = libsrc/interface
#
include ../makefile.inc
#
