foreach(mode IN ITEMS default 1 0)
  set(options)
  if(NOT mode STREQUAL "default")
    list(APPEND options -setnumber Mesh.OptimizeQuadsSmartLaplacian ${mode})
  endif()
  execute_process(
    COMMAND "${GMSH_EXECUTABLE}" "${TEST_GEO}" -parse_and_exit -nopopup
            -v 6 ${options}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  set(log "${output}${error}")
  if(NOT status EQUAL 0 OR log MATCHES "Error[ ]*:")
    message(FATAL_ERROR "Smoothing mode ${mode} failed:\n${log}")
  endif()
  if(NOT log MATCHES "OptimizeQuadsFast: 1 faces, 0 topology changes" OR
     NOT log MATCHES "validity=PASS invalid\\[T/Q\\]=0/0")
    message(FATAL_ERROR "The fixed four-quad star changed topology/validity:\n${log}")
  endif()
  string(FIND "${log}" "initial smoothing begin" initial_begin)
  string(FIND "${log}" "initial smoothing end" initial_end)
  string(FIND "${log}" "loop round=1 phase=valence begin" valence)
  string(FIND "${log}" "loop round=1 phase=swap begin" swaps)
  string(FIND "${log}" "loop round=1 phase=merge begin" merge)
  string(FIND "${log}" "loop end" loop_end)
  string(FIND "${log}" "terminal Winslow begin" polish_begin)
  string(FIND "${log}" "terminal Winslow end" polish_end)
  string(FIND "${log}" "final split begin" split_begin)
  string(FIND "${log}" "final split end" split_end)
  if(initial_begin LESS 0 OR initial_end LESS initial_begin OR
     valence LESS initial_end OR swaps LESS valence OR merge LESS swaps OR
     loop_end LESS merge OR polish_begin LESS loop_end OR polish_end LESS polish_begin OR
     split_begin LESS polish_end OR split_end LESS split_begin OR
     NOT log MATCHES "end valence=0 swaps=0 merges=0 moved=0" OR
     NOT log MATCHES "loop end rounds=1 reason=topology-idle")
    message(FATAL_ERROR "Expected initial smoothing, ordered rounds to idle, final split:\n${log}")
  endif()
  string(REGEX MATCHALL "terminal Winslow sweep=[1-4] moved=[0-9]+" polish_sweeps "${log}")
  list(LENGTH polish_sweeps polish_count)
  if(NOT polish_count EQUAL 4)
    message(FATAL_ERROR "Expected exactly four terminal Winslow sweeps:\n${log}")
  endif()
  string(SUBSTRING "${log}" ${polish_begin} -1 polish_tail)
  if(polish_tail MATCHES "loop round=" OR polish_tail MATCHES "nodeSmartLaplacian" OR
     polish_tail MATCHES "centroidTried=[1-9]")
    message(FATAL_ERROR "Topology/Smart restarted during terminal Winslow:\n${log}")
  endif()
  string(SUBSTRING "${log}" ${split_begin} -1 tail)
  if(tail MATCHES "stage=(valence|swap|merge|round|initial|polish)" OR tail MATCHES "loop round=")
    message(FATAL_ERROR "Optimization resumed after final splitting:\n${log}")
  endif()
  if(mode STREQUAL "default")
    if(NOT log MATCHES "nodeSmartLaplacian stage=initial" OR
       NOT log MATCHES "nodeWinslow stage=initial")
      message(FATAL_ERROR "Default batch must attempt both nodal methods:\n${log}")
    endif()
  elseif(mode STREQUAL "1")
    if(NOT log MATCHES "nodeSmartLaplacian stage=initial" OR log MATCHES "nodeWinslow stage=initial")
      message(FATAL_ERROR "Pure Smart mode was not selected:\n${log}")
    endif()
  elseif(log MATCHES "nodeSmartLaplacian" OR NOT log MATCHES "nodeWinslow stage=initial")
    message(FATAL_ERROR "Centroid/Winslow mode was not selected:\n${log}")
  endif()
endforeach()
