foreach(mode IN ITEMS default 1 0)
  set(options)
  if(NOT mode STREQUAL "default")
    list(APPEND options -setnumber Mesh.QuadqsSmartLaplacian ${mode})
  endif()
  execute_process(
    COMMAND "${GMSH_EXECUTABLE}" "${TEST_GEO}" -parse_and_exit -nopopup
            -v 6 ${options}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  set(log "${output}${error}")
  if(NOT status EQUAL 0 OR log MATCHES "Error[ ]*:")
    message(FATAL_ERROR "Smoothing mode ${mode} failed:\n${log}")
  endif()
  if(NOT log MATCHES "OptimizeQuadsFast: 1 faces, 0 topology changes" OR
     NOT log MATCHES "validity=PASS invalid\\[T/Q\\]=0/0")
    message(FATAL_ERROR "The fixed four-quad star changed topology/validity:\n${log}")
  endif()
  if(mode STREQUAL "default")
    string(FIND "${log}" "final SmartLaplacian end" smart_end)
    string(FIND "${log}" "final Winslow polish begin" winslow_begin)
    if(smart_end LESS 0 OR winslow_begin LESS smart_end OR
       NOT log MATCHES "final SmartLaplacian end sweeps=[1-3] acceptedNodes=1" OR
       NOT log MATCHES "final Winslow polish end sweeps=1 acceptedNodes=1")
      message(FATAL_ERROR "Expected one productive Winslow pass after Smart:\n${log}")
    endif()
    string(SUBSTRING "${log}" ${winslow_begin} -1 tail)
    if(tail MATCHES "centroidTried=[1-9]" OR tail MATCHES "round=[0-9]+ begin")
      message(FATAL_ERROR "Final Winslow ran centroid/topology operations:\n${log}")
    endif()
  else()
    if(log MATCHES "Winslow polish")
      message(FATAL_ERROR "An explicit historical mode ran extra Winslow:\n${log}")
    endif()
    if(mode STREQUAL "1" AND NOT log MATCHES "final SmartLaplacian end")
      message(FATAL_ERROR "Pure Smart mode was not selected:\n${log}")
    endif()
    if(mode STREQUAL "0" AND log MATCHES "final SmartLaplacian")
      message(FATAL_ERROR "Legacy mode unexpectedly ran Smart:\n${log}")
    endif()
  endif()
endforeach()
