.\" $Id: gmsh.1,v 1.60 2004-12-27 00:47:04 geuzaine Exp $
.TH Gmsh 1 "26 December 2004" "Gmsh 1.57" "Gmsh Manual Pages"
.UC 4
.\" ********************************************************************
.SH NAME
Gmsh \- an automatic three-dimensional finite element mesh generator
with built-in pre- and post-processing facilities
.\" ********************************************************************
.SH SYNOPSIS
.B gmsh [file(s)] [option(s)]
.\" ********************************************************************
.SH DESCRIPTION
\fIGmsh\fR is an automatic three-dimensional finite element mesh
generator (primarily Delaunay) with build-in CAD and post-processing
facilities. Its design goal is to provide a simple meshing tool for
academic problems with parametric input and up to date visualization
capabilities.
.PP
\fIGmsh\fR is built around four modules: geometry, mesh, solver and
post-processing. The specification of any input to these modules is
done either interactively using the graphical user interface or in
ASCII text files using \fIGmsh\fR's own scripting language.
.\" ********************************************************************
.SH GEOMETRY OPTIONS
.TP 4
.B \-0
parse all input files, output unrolled geometry, and exit. 
.\" ********************************************************************
.SH MESH OPTIONS
.TP 4
.B \-1
perform the one-dimensional mesh, i.e., discretize all the curves in
the geometry.
.TP 4
.B \-2
perform the two-dimensional mesh, i.e., discretize all the surfaces in
the geometry.
.TP 4
.B \-3
perform the three-dimensional mesh, i.e., discretize all the volumes in
the geometry.
.TP 4
.B \-saveall
save all elements (and discard all physical group definitions).
.TP 4
.B \-o file
specify mesh output file name.
.TP 4
.B \-format string
set output mesh format (msh, unv, gref).
.TP 4
.B \-algo string
select mesh algorithm (iso, tri, aniso, netgen).
.TP 4
.B \-smooth int
set number of smoothing steps.
.TP 4
.B \-optimize
optimize quality of tetrahedral elements.
.TP 4
.B \-order int
set mesh order (1, 2).
.TP 4
.B \-scale float
set global scaling factor to the model.
.TP 4
.B \-meshscale float
set global scaling factor to the mesh output.
.TP 4
.B \-clscale float
set global scaling factor to the mesh characteristic lengths in the
model.
.TP 4
.B \-rand float
set random perturbation factor.
.TP 4
.B \-bgm file
load the post-processing view in file as the current background mesh.
.TP 4
.B \-constrain
constrain the background mesh with the characteristic lengths of the
model.
.TP 4
.B \-histogram
print mesh quality histogram.
.TP 4
.B \-extrude
use the old extrusion mesh generator.
.TP 4
.B \-recombine
recombine meshes from the old extrusion mesh generator.
.TP 4
.B \-interactive
display the 2D mesh construction interactively if the anisotropic mesh
algorithm is selected.
.\" ********************************************************************
.SH POST-PROCESSING OPTIONS
.TP 4
.B \-noview
hide all views at startup.
.TP 4
.B \-link int
choose link mode between post-processing views (0, 1, 2, 3, 4).
.TP 4
.B \-combine
combine input views into multi-time-step ones.
.\" ********************************************************************
.SH DISPLAY OPTIONS
.TP 4
.B \-nodb
suppress the double buffer. Use this options if you use \fIGmsh\fR on
a remote host without GLX.
.TP 4
.B \-fontsize int
specify the font size for the GUI.
.TP 4
.B \-scheme string
specify the FLTK GUI scheme.
.TP 4
.B \-display string
specify display.
.\" ********************************************************************
.SH OTHER OPTIONS
.TP 4
.B \-a, \-g, \-m, \-s, \-p
start in automatic, geometry, mesh, solver or post-processing mode.
.TP 4
.B \-pid
print pid on stdout.
.TP 4
.B \-v int
set verbosity level.
.TP 4
.B \-nopopup
don't popup dialog windows in scripts.
.TP 4
.B \-string "string"
parse string before project file.
.TP 4
.B \-option file
parse option file before GUI creation.
.TP 4
.B \-convert file file
perform batch conversion of views and meshes into latest file formats.
.TP 4
.B \-version
show version number.
.TP 4
.B \-info
show detailed version information.
.TP 4
.B \-help
show help message.
.\" ********************************************************************
.SH AUTHORS
Christophe Geuzaine (geuzaine@acm.caltech.edu) and Jean-Francois
Remacle (remacle@gce.ucl.ac.be). 
.\" ********************************************************************
.SH SEE ALSO
.BR getdp (1),
.br
Gmsh examples (\fI/usr/share/doc/gmsh-*/\fR),
.br
Gmsh homepage (\fIhttp://www.geuz.org/gmsh/\fR).
.PP
The full documentation for Gmsh is maintained as a Texinfo manual.  If
the
.B info
and
.B gmsh
programs are properly installed at your site, the command
.IP
.B info gmsh
.PP
should give you access to the complete manual.
