import gmsh
gmsh.initialize()
gmsh.open('as1-tu-203.stp')
gmsh.option.setNumber('Mesh.StlLinearDeflection', 1)
gmsh.option.setNumber('Mesh.StlLinearDeflectionRelative', 0)
gmsh.option.setNumber('Mesh.StlAngularDeflection', 0.5)
gmsh.option.setNumber('Mesh.RecombinationAlgorithm', 0)
gmsh.option.setNumber('Mesh.RecombineOptimizeTopology', 0)
gmsh.option.setNumber('Mesh.RecombineNodeRepositioning', 0)
gmsh.option.setNumber('Mesh.RecombineMinimumQuality', 1e-3)
gmsh.model.mesh.importStl()
#gmsh.model.mesh.removeDuplicateNodes()
#gmsh.model.mesh.reclassifyNodes()
gmsh.model.mesh.recombine()
gmsh.fltk.run()
gmsh.finalize()
