#
# Makefile for visualization library
#
src = stlmeshing.cpp mvdraw.cpp vscsg.cpp vsmesh.cpp vsocc.cpp vssolution.cpp meshdoc.cpp
#
lib = vis
libpath = libsrc/visualization
#
#
include ../makefile.inc
#


