#
# Makefile for general purpose data types
#
src = array.cpp bitarray.cpp hashtabl.cpp symbolta.cpp table.cpp flags.cpp \
	spbita2d.cpp seti.cpp optmem.cpp sort.cpp mystring.cpp parthreads.cpp \
	moveablemem.cpp dynamicmem.cpp ngexception.cpp
#	
lib = gen
libpath = libsrc/general
#
include ../makefile.inc

