#ifndef _HELP_H_
#define _HELP_H_

static char txt_help[]=
"\n"
"  (x)         stands for \"press x\"\n"
"  (x-y)       stands for \"press x and, keeping it down, press y\"\n"
"  C, M and S  stand for Control, Meta (or Alt) and Shift\n"
"\n"
"MOUSE:\n"
"\n"
"  move        when passing over the entity, highlight it and\n"
"                display its properties on the bottom line\n"
"              size a rubber zoom started with (C-left)\n"
"\n"
"  (left)      apply Y rotation (horizontal move)\n"
"              apply X rotation (vertical move)\n"
"              accept a rubber zoom started by (C-left)\n" 
"  (middle)    apply Z rotation (horizontal move)\n"
"              zoom (vertical move)\n"
"              cancel a rubber zoom\n"
"  (right)     pan X (horizontal move)\n"
"              pan Y (vertical move)\n"
"              cancel a rubber zoom\n"
"              popup menu on module name\n"
"              popup menu on post processor toggle buttons\n"
"\n"
"  (C-left)    start a rubber zoom\n" 
"  (C-middle)  re-orthogonalise viewport\n" 
"  (C-right)   reset viewport to default\n"   
"\n"
"KEYBOARD:\n"
"\n"
"No modifier: basic module interaction\n"
"\n"
"  (0)         reparse file\n"
"  (1),(f1)    mesh lines\n"
"  (2),(f2)    mesh surfaces\n"
"  (3),(f3)    mesh volumes\n"
"  (g)         go to geometry module\n"
"  (m)         go to mesh module\n"
"  (p)         go to post processor module\n"
"\n"
"Control modifier: popup file menus\n"
"\n"
"  (C-a),(C-c) abort mesh thread\n"
"  (C-q)       quit\n"
"  (C-o)       hide/show open file dialog\n" 
"  (C-p)       hide/show print dialog\n"
"  (C-m)       hide/show merge file dialog\n" 
"  (C-s)       quick mesh save\n"
"  (C-S-s)     hide/show save mesh dialog\n"
"\n"
"Shift modifier: popup option menus\n"
"\n"
"  (S-g)       hide/show geometry options\n"
"  (S-i)       hide/show info window\n" 
"  (S-m)       hide/show mesh options\n"
"  (S-o)       hide/show miscellaneous options\n" 
"  (S-p)       hide/show post processor general options\n"
"  (S-v)       hide/show viewport options\n" 
"\n"
"Meta (Alt) modifier: quick shortcuts (no popup)\n"
"\n"
"  (M-a)       hide/show 2D axes\n" 
"  (M-S-a)     hide/show 3D axes\n" 
"  (M-b)       hide/show all post processing scales\n"
"  (M-c)       alternate between predefined color modes\n"
"  (M-d)       alternate between mesh wireframe, hidden lines and shading modes\n"
"  (M-f)       toggle redraw mode (fast/display all)\n" 
"  (M-h)       toggle highlight mode\n"
"  (M-l)       hide/show geometry lines\n"
"  (M-S-l)     hide/show mesh lines\n"
"  (M-m)       toggle all mesh entities visibility\n"
"  (M-o)       change projection mode\n"
"  (M-p)       hide/show geometry points\n"
"  (M-S-p)     hide/show mesh points\n"
"  (M-s)       hide/show geometry surfaces\n"
"  (M-S-s)     hide/show mesh surfaces\n"
"  (M-v)       hide/show geometry volumes\n"
"  (M-S-v)     hide/show mesh volumes\n"
"  (M-x)       set X view\n" 
"  (M-y)       set Y view\n" 
"  (M-z)       set Z view\n" 
"  (M-t)       alternate intervals mode in post-processing\n" 
"\n"
;


#endif
