/* $Id: Help.h,v 1.6 2000-12-26 11:59:06 geuzaine Exp $ */
#ifndef _HELP_H_
#define _HELP_H_

static char txt_help[]=
"\n"
"  (x)          stands for \"press x\"\n"
"  (x-y)        stands for \"press x and, keeping it down, press y\"\n"
"  (x-y-z)      stands for \"press x and, keeping it down, press y and z\"\n"
"  C, M and S   stand for Control, Meta (or Alt) and Shift\n"
"\n"
"MOUSE:\n"
"\n"
"  move         . highlight the elementary geometrical entity \n"
"                 currently under the mouse pointer and display\n"
"                 its properties in the status bar\n"
"               . size a rubber zoom started with (C-left)\n"
"\n"
"  (left)       . rotate\n"
"               . accept a rubber zoom started by (C-left)\n" 
"  (middle)     . zoom (isotropic)\n"
"               . cancel a rubber zoom\n"
"  (right)      . pan\n"
"               . cancel a rubber zoom\n"
"               . pop up menu on module name\n"
"               . pop up menu on post-processing view button\n"
"\n"
"  (C-left)     start (anisotropic) rubber zoom\n" 
"  (C-middle)   orthogonalize display\n" 
"  (C-right)    reset viewpoint to default\n"   
"\n"
"KEYBOARD:\n"
"\n"
"No modifier: basic module interaction\n"
"\n"
"  (0)          reload input file\n"
"  (1), (F1)    mesh curves\n"
"  (2), (F2)    mesh surfaces\n"
"  (3), (F3)    mesh volumes\n"
"  (g)          go to geometry module\n"
"  (m)          go to mesh module\n"
"  (p)          go to post processor module\n"
"\n"
"Control modifier: file menu\n"
"\n"
"  (C-q)        quit\n"
"  (C-o)        hide/show open file dialog\n" 
"  (C-p)        hide/show save/print dialog\n"
"  (C-m)        hide/show merge file dialog\n" 
"  (C-s)        quick mesh save\n"
"\n"
"Shift modifier: pop up option menus\n"
"\n"
"  (S-g)        hide/show geometry options\n"
"  (S-i)        hide/show statistics window\n" 
"  (S-m)        hide/show mesh options\n"
"  (S-o)        hide/show miscellaneous options\n" 
"  (S-p)        hide/show post-processing general options\n"
"  (S-v)        hide/show viewpoint options\n" 
"\n"
"Meta (Alt) modifier: quick shortcuts (no pop up)\n"
"\n"
"  (M-a)        hide/show small axes\n" 
"  (M-S-a)      hide/show big moving axes\n" 
"  (M-b)        hide/show all post processing scales\n"
"  (M-c)        alternate between predefined color schemes\n"
"  (M-d)        alternate between mesh wire frame, hidden lines\n"
"               and shading modes\n"
"  (M-f)        toggle redraw mode (fast/full)\n" 
"  (M-h)        toggle highlight mode\n"
"  (M-l)        hide/show geometry lines\n"
"  (M-S-l)      hide/show mesh lines\n"
"  (M-m)        toggle visibility of all mesh entities\n"
"  (M-o)        change projection mode\n"
"  (M-p)        hide/show geometry points\n"
"  (M-S-p)      hide/show mesh points\n"
"  (M-s)        hide/show geometry surfaces\n"
"  (M-S-s)      hide/show mesh surfaces\n"
"  (M-t)        alternate intervals mode for all post-processing\n" 
"               views\n" 
"  (M-v)        hide/show geometry volumes\n"
"  (M-S-v)      hide/show mesh volumes\n"
"  (M-x)        set X view\n" 
"  (M-y)        set Y view\n" 
"  (M-z)        set Z view\n" 
"\n"
;


#endif
