#!/bin/sh

if [ $# -lt 1 ] ; then
  echo "Usage: addId files" 1>&2
  exit 1
else 
#  echo "/* \$Id\$ */" > _tmp_string_
  echo "# \$Id\$" > _tmp_string_
#  echo "c \$Id\$" > _tmp_string_

  for file in $@; do
    echo Modifying $file
    mv $file $file~
    cat _tmp_string_ $file~ > $file
  done

  rm -f _tmp_string_
fi


