#!/bin/sh

#if [ $# = 0 ] ; then
#  echo "Usage: tut2html files"
#  exit 1
#fi

#enscript -Ecpp --color -Whtml --toc -pt.html $*
enscript -Ecpp --color -Whtml --toc -pt.html README.txt *.geo

cat t.html | \
sed "s/<FONT COLOR=\"#BC8F8F\"><B>//g" | \
sed "s/<B><FONT COLOR=\"#5F9EA0\">//g" | \
sed "s/<B><FONT COLOR=\"#A020F0\">//g" | \
sed "s/<B><FONT COLOR=\"#0000FF\">//g" | \
sed "s/<\/FONT><\/B>//g" > tutorial.html

rm -f t.html

echo output moved to tutorial.html
