src = adfront2.cpp adfront3.cpp geomsearch.cpp global.cpp \
        meshtool.cpp \
        netrule2.cpp netrule3.cpp parser2.cpp parser3.cpp ruler2.cpp ruler3.cpp \
        meshtype.cpp meshclass.cpp improve2.cpp smoothing2.cpp improve3.cpp smoothing3.cpp \
	improve2gen.cpp meshing2.cpp meshing3.cpp  \
	localh.cpp delaunay.cpp topology.cpp clusters.cpp \
	tetrarls.cpp triarls.cpp quadrls.cpp meshfunc.cpp meshfunc2d.cpp \
	refine.cpp bisect.cpp zrefine.cpp secondorder.cpp hprefinement.cpp \
	boundarylayer.cpp specials.cpp msghandler.cpp \
	pyramidrls.cpp pyramid2rls.cpp prism2rls.cpp curvedelems.cpp curvedelems2.cpp
#
lib = mesh
libpath = libsrc/meshing
#
include ../makefile.inc
#
