#
# Makefile for geometric library
#
src =  geom2d.cpp geom3d.cpp  \
	geomtest3d.cpp adtree.cpp transform3d.cpp geomfuncs.cpp

# reftrans.cpp rot3d.cpp
#
lib = gprim
libpath = libsrc/gprim
#
#
include ../makefile.inc
#
