/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testlibc_Gmsh */

#ifndef _Included_com_example_testlibc_Gmsh
#define _Included_com_example_testlibc_Gmsh

void requestRender();

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_testlibc_Gmsh_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    loadFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_testlibc_Gmsh_loadFile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    initView
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_example_testlibc_Gmsh_initView
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    drawView
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_testlibc_Gmsh_drawView
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    setTranslation
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_example_testlibc_Gmsh_setTranslation
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    setScale
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_example_testlibc_Gmsh_setScale
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    setRotate
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_example_testlibc_Gmsh_setRotate
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    setShow
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_example_testlibc_Gmsh_setShow
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    getOnelabInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_testlibc_Gmsh_getOnelabInstance
  (JNIEnv *, jobject);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    getParams
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_testlibc_Gmsh_getParams
  (JNIEnv *, jobject);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    setParam
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_testlibc_Gmsh_setParam
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    getPView
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_testlibc_Gmsh_getPView
  (JNIEnv *, jobject);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    setPView
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_testlibc_Gmsh_setPView
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_example_testlibc_Gmsh
 * Method:    onelabCB
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_testlibc_Gmsh_onelabCB
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
