# Gmsh - Copyright (C) 1997-2008 C. Geuzaine, J.-F. Remacle
#
# See the LICENSE.txt file for license information. Please report all
# bugs and problems to <gmsh@geuz.org>.

include ../../variables

default:
	@cd src && ${MAKE}

cpobj:
	@cd src && ${MAKE} cpobj

clean:
	@cd src && ${MAKE} clean

depend:
	@cd src && ${MAKE} depend
